definitions:
  product:
    type: object
    required:
      - product_name
    properties:
      product_name:
        type: string
      product_price:
        type: number
        format: float

paths:
  /products:
    get:
      operationId: controllers.product_controller.get_all
      summary: Get products by page_number and page_size
      description: Get products by page_number and page_size
      tags:
        - product
      parameters:
        - name: page_number
          in: query
          type: integer
        - name: page_size
          in: query
          type: integer
      responses:
        200:
          description: OK

    post:
      operationId: controllers.product_controller.create
      summary: Create an product
      tags:
        - product
      parameters:
        - name: product_data
          in: body
          schema:
            $ref: "#/definitions/product"
          required: true
      responses:
        200:
          description: OK
  /products/{product_id}:
    get:
      operationId: controllers.product_controller.get_by_id
      summary: Get product by id
      tags:
        - product
      parameters:
        - name: product_id
          in: path
          required: true
          type: integer
      responses:
        200:
          description: OK
    delete:
      operationId: controllers.product_controller.delete
      summary: Delete product by id
      tags:
        - product
      parameters:
        - name: product_id
          in: path
          required: true
          type: integer
      responses:
        200:
          description: OK
    put:
      operationId: controllers.product_controller.update
      summary: Update product by id
      tags:
        - product
      parameters:
        - name: product_id
          in: path
          required: true
          type: integer
        - name: product_data
          in: body
          schema:
            $ref: "#/definitions/product"
          required: true
      responses:
        200:
          description: OK